### ISSUE TITLE
version in code does not match that in tagged releases.

### ISSUE THREAD

**Issue by gedw99** [vorlif/xspreak#3]
the version is hardcoded but the tagged release does not match. 

Here is where we hard code the version number.

https://github.com/vorlif/xspreak/blob/15a5c7eddac3fdc55e0550308581516aee9c491e/commands/root.go#L24C18-L24C18 

Below it shows the wrong version number..

```sh
go install github.com/vorlif/xspreak@v0.10.0
 xspreak --version
xspreak version v0.9.0
```

common thing but annoying .. 

So maybe just write a makefile target to do both so it does not happen again.
It would create the tag at the same time as updating the version that is hardcoded in the golang code.

ok I see your doing it in CI at https://github.com/vorlif/xspreak/blob/main/.github/workflows/release.yml

so modify this to do a sed update of that golang version line then ?

**Comment by vorlif** [comment]
Hi @gedw99,

Thanks for the report. I agree with you, it's not nice. I'll try to set the version number with #4 automatically.

**Comment by gedw99** [comment]
Thankyou . I will have a look.
